# numpy 
1. Numpy 설치 
    Numpy는 pip를 통해 쉽게 설치가 가능하다.  
    $pip install numpy

In [2]:
!pip3 install numpy


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip install --upgrade pip


In [3]:
import numpy as np

# 1. Numpy 배열 생성
numpy 에서 가장 중요한 객체는 ndarray로 다차원 배열을 생성하고 관리할 수 있다.

In [4]:
# 1. list를 배열로 변환
arr = [1,2,3,4,5]
type(arr)

print(arr)

[1, 2, 3, 4, 5]


In [5]:
ndarray = np.array(arr)
type(ndarray)

print(ndarray)

[1 2 3 4 5]


# 2. 다차원 배열

In [6]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


# 3. ndarray 배열의 속성  
배열의 중요한 속성들을 확인하는 것은 배열의 구조를 파악하는데 필수적이다.  
배열의 구조에 따라 데이터를 조작하는 방식이 달라지기 때문이다.

In [7]:
print('ndarray.shape:', ndarray.shape) # 배열의 차원을 확인
print('arr_2d.shape:', arr_2d.shape) # 배열의 차원을 확인

ndarray.shape: (5,)
arr_2d.shape: (2, 3)


In [8]:
print('ndarray.dtype:', ndarray.dtype) # 데이터의 타입을 확인
print('arr_2d.dtype:', arr_2d.dtype) # 데이터의 타입을 확인

ndarray.dtype: int64
arr_2d.dtype: int64


In [9]:
print('ndarray.ndim:', ndarray.ndim) # 데이터의 차원 수 확인
print('arr_2d.ndim:', arr_2d.ndim) # 데이터의 차원 수 확인

ndarray.ndim: 1
arr_2d.ndim: 2


# 4. 배열 초기화
numpy는 배열을 초기화하는 여러 방법을 제공한다.

In [10]:
arr_2d = np.zeros((3,3)) # 3x3 의 배열을 생성
print(arr_2d)
print("--------")

arr_2d = np.ones((2,2)) # 2x2 의 배열을 생성하고 값을 1로 채움
print(arr_2d)
print("--------")

arr_2d = np.full((3,3), 7) # 3x3 의 배열을 생성하고 값을 7로 채움
print(arr_2d)
print("--------")

arr_2d = np.random.random((2,2)) # 2x2 의 배열을 생성하고 값을 랜덤하게 채움
print(arr_2d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
--------
[[1. 1.]
 [1. 1.]]
--------
[[7 7 7]
 [7 7 7]
 [7 7 7]]
--------
[[0.44716147 0.85840147]
 [0.61230903 0.87535761]]


# 배열 연산 및 슬라이싱
numpy는 백터화된 연산을 지원하여 배열 간의 연산을 매우 효율적으로 처리한다.

In [11]:
# 파이썬 리스트 간의 덧샘
# 두 배열을 합친다.

arr1 = [1,2,3]
arr2 = [4,5,6]
result = arr1 + arr2
print(result)

[1, 2, 3, 4, 5, 6]


In [12]:
# list 간 덧샘
# 백터 연산을 통해 두 리스트의 같은 인덱스 위치에 값을 더한다.

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
result = arr1 + arr2
print(result)

[5 7 9]


In [13]:
# 배열 간의 행렬 곱
# 백터 연산을 통해 두 리스트의 같은 인덱스 위치에 값을 더한다.

result = arr1 * arr2
print(result)

[ 4 10 18]


In [14]:
# 배열 간 행렬 곱
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

# 연산 과정
# 1*5 + 2*7 = 5, 14
# 1*6 + 2*8 = 6, 16
# 3*5 + 4*7 = 15, 28
# 3*6 + 4*8 = 18, 32
result = np.dot(arr1, arr2)
print(result)

[[19 22]
 [43 50]]


In [15]:
# 1차원 배열 슬라이싱
arr = np.array([1,2,3,4,5])
print(arr[1:4]) # 1번 인덱스에서 4미만 인덱스까지 

[2 3 4]


In [16]:
# 2차원 배열 슬라이싱
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr_2d)
print(arr_2d[:2, 1:])

# 결과
# [[ : 2 - 0부터 2까지 -> 행을 지시
#   1: ]]  - 1번 부터 마지막까지 -> 열을 지시

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]


# 배열의 형태 변경

In [17]:
arr = np.array([1,2,3,4,5,6])
reshaped_arr = arr.reshape((2,3)) # 2*3 배열로 변경
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [18]:
# 조건별 값 선택
arr = np.array([1,2,3,4,5])
condition = arr>3
filtered_arr = arr[condition]
print('condition', condition)
print('filtered_arr', filtered_arr)

condition [False False False  True  True]
filtered_arr [4 5]


# 고차원 배열 연산 및 고급 기능

In [19]:
# 고차원 배열
# numpy는 1차원 배열뿐만 아니라 3차원, 4차원 이상의 고차원 배열도 쉽게 다룰 수 있다.
arr_3d = np.random.random((3,3,3)) # 3*3*3 차원 배열 생성
print(arr_3d)

[[[0.50769523 0.81035282 0.19781277]
  [0.8533396  0.01538163 0.41926472]
  [0.52468402 0.55166188 0.32730678]]

 [[0.05867864 0.80996729 0.17340943]
  [0.11613922 0.26259831 0.83229188]
  [0.20797225 0.88437191 0.86119034]]

 [[0.38401178 0.70546795 0.23817941]
  [0.50397186 0.08810259 0.20071672]
  [0.16960953 0.35819102 0.60879013]]]


In [20]:
# 브로드캐스팅
# 브로드캐스팅은 서로 다른 크기의 배열 간의 연산을 가능하게 하는 강력한 기능이다.
arr1 = np.array([[1], [2], [3]])
arr2 = np.array([4,5,6])
print(arr1)
print(arr2)

result = arr1 + arr2
print(result)

# 연산과정
# 1+4, 1+5, 1+6
# 2+4, 2+5, 2+6
# 3+4, 3+5, 3+6



[[1]
 [2]
 [3]]
[4 5 6]
[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [21]:
# 고급 인덱싱 및 슬라이싱
# numpy는 불리언 배열과 정수 배열을 사용하여 복잡한 인덱싱을 지원한다.
arr = np.array([10, 20, 30, 40])
bool_arr = np.array([True, False, True, False])
filtered = arr[bool_arr]
print(filtered)

[10 30]


# 배열 합치기 및 나누기
배열을 수평 또는 수직으로 합치거나 나누는 방법이다.

In [22]:
# 배열 합치기
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

# axis는 (0,1)의 값을 가질 수 있다.
# 0 = 행을 기준으로 합치는 조건
# 1 = 열을 기준으로 합치는 조건
concatenated = np.concatenate((arr1, arr2), axis=0) # 행 기준
# concatenated = np.concatenate((arr1, arr2), axis=0) # 열 기준
print(concatenated)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [23]:
# 배열 나누기
arr = np.array([[1, 2, 3], [4, 5, 6]])
# split 자르는 메서드
# axis는 (0,1)의 값을 가질 수 있다.
# 0 = 행을 기준으로 합치는 조건
# 1 = 열을 기준으로 합치는 조건
split_arr = np.split(arr, 2, axis=0)
print(split_arr)

[array([[1, 2, 3]]), array([[4, 5, 6]])]


# 고급 : Numpy 성능 최적화

In [24]:
# 벡터화 연산과 for 루프의 비교
arr = np.random.random(1000000) # 100만개의 난수 생성

%timeit np.sum(arr)

# for 루프의 연산
def slow_sum(arr):
  total = 0
  for i in arr:
    total += i
  return total


%timeit slow_sum(arr)

518 μs ± 127 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
90.4 ms ± 3.82 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [25]:
# 메모리 관리 및 배열 복사
# numpy는 메모리를 활용해 효율적인 배열 복사를 지원하며, 명시적으로 복사하지 않으면 같은 메모리 주소를 공유한다.

arr = np.array([1,2,3])
arr_copy = arr.copy()
print(arr_copy)

[1 2 3]


In [26]:
# 고급 수학 함수
# NumPy는 선형 대수, 푸리에 변환, 통계 함수 등 고급 수학 함수들을 제공한다.

# 선형 대수
# 역행렬
# 정사각 행렬 𝐴A에 대해, 그 행렬과 곱했을 때 단위 행렬(identity matrix)을 만들어내는 행렬이다. 쉽게 말하면, 역행렬은 행렬을 "원래 상태로 돌려놓는" 역할을 하는 행렬이다.
arr = np.array([[1, 2], [3, 4]])
inverse = np.linalg.inv(arr)  # 역행렬 구하기
print("역행렬 : ")
print(inverse)
print()

# 표준편차
mean = np.mean(arr)
std_dev = np.std(arr)
print("통계 함수 : ")
print(std_dev)

역행렬 : 
[[-2.   1. ]
 [ 1.5 -0.5]]

통계 함수 : 
1.118033988749895
